# Neuron Network - Lab

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

### Part 1: Load  data

Import "bank-data.csv"

In [2]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/CPE_KMUTT/Year3/Semester_1-68/CPE342_MachineLearning/CPE342_Lab/CPE342_Lab_Assignment5_NeuralNetwork/bank-data.csv', sep=';')
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,no,1787,no,no,cellular,19,oct,79,1,-1,0,unknown,no
1,33,services,married,secondary,no,4789,yes,yes,cellular,11,may,220,1,339,4,failure,no
2,35,management,single,tertiary,no,1350,yes,no,cellular,16,apr,185,1,330,1,failure,no
3,30,management,married,tertiary,no,1476,yes,yes,unknown,3,jun,199,4,-1,0,unknown,no
4,59,blue-collar,married,secondary,no,0,yes,no,unknown,5,may,226,1,-1,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,no,-333,yes,no,cellular,30,jul,329,5,-1,0,unknown,no
4517,57,self-employed,married,tertiary,yes,-3313,yes,yes,unknown,9,may,153,1,-1,0,unknown,no
4518,57,technician,married,secondary,no,295,no,no,cellular,19,aug,151,11,-1,0,unknown,no
4519,28,blue-collar,married,secondary,no,1137,no,no,cellular,6,feb,129,4,211,3,other,no
4520,44,entrepreneur,single,tertiary,no,1136,yes,yes,cellular,3,apr,345,2,249,7,other,no

### Part 2: Preprocess data

Preprocess the dataset as you have done before

#### 2.1 Binary encoding

Use LabelEncoder to encode the following columns:
- y
- default
- housing
- loan

In [3]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder instance
le = LabelEncoder()
df['y'] = le.fit_transform(df['y'])
df['default'] = le.fit_transform(df['default'])
df['housing'] = le.fit_transform(df['housing'])
df['loan'] = le.fit_transform(df['loan'])
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,30,unemployed,married,primary,0,1787,0,0,cellular,19,oct,79,1,-1,0,unknown,0
1,33,services,married,secondary,0,4789,1,1,cellular,11,may,220,1,339,4,failure,0
2,35,management,single,tertiary,0,1350,1,0,cellular,16,apr,185,1,330,1,failure,0
3,30,management,married,tertiary,0,1476,1,1,unknown,3,jun,199,4,-1,0,unknown,0
4,59,blue-collar,married,secondary,0,0,1,0,unknown,5,may,226,1,-1,0,unknown,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,services,married,secondary,0,-333,1,0,cellular,30,jul,329,5,-1,0,unknown,0
4517,57,self-employed,married,tertiary,1,-3313,1,1,unknown,9,may,153,1,-1,0,unknown,0
4518,57,technician,married,secondary,0,295,0,0,cellular,19,aug,151,11,-1,0,unknown,0
4519,28,blue-collar,married,secondary,0,1137,0,0,cellular,6,feb,129,4,211,3,other,0
4520,44,entrepreneur,single,tertiary,0,1136,1,1,cellular,3,apr,345,2,249,7,other,0

#### 2.2 Convert categorical variables into dummy columns

(1) Use pd.get_dummies to convert the following categorical variales into dummy columns
- job
- maritial
- education
- contact
- month
- poutcome

(2) Drop columns that have been converted

In [4]:
# Apply get_dummies to the following categorical column
df = pd.get_dummies(df, columns=['job', 'marital', 'education', 'contact', 'month', 'poutcome'])
df

,age,default,balance,housing,loan,day,duration,campaign,pdays,previous,...,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,poutcome_failure,poutcome_other,poutcome_success,poutcome_unknown
0,30,0,1787,0,0,19,79,1,-1,0,...,False,False,False,False,True,False,False,False,False,True
1,33,0,4789,1,1,11,220,1,339,4,...,False,False,True,False,False,False,True,False,False,False
2,35,0,1350,1,0,16,185,1,330,1,...,False,False,False,False,False,False,True,False,False,False
3,30,0,1476,1,1,3,199,4,-1,0,...,True,False,False,False,False,False,False,False,False,True
4,59,0,0,1,0,5,226,1,-1,0,...,False,False,True,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4516,33,0,-333,1,0,30,329,5,-1,0,...,False,False,False,False,False,False,False,False,False,True
4517,57,1,-3313,1,1,9,153,1,-1,0,...,False,False,True,False,False,False,False,False,False,True
4518,57,0,295,0,0,19,151,11,-1,0,...,False,False,False,False,False,False,False,False,False,True
4519,28,0,1137,0,0,6,129,4,211,3,...,False,False,False,False,False,False,False,True,False,False
4520,44,0,1136,1,1,3,345,2,249,7,...,False,False,False,False,False,False,False,True,False,False

#### 2.3 Train/Test separation

Perform hold-out method
- 60% training set
- 40% testing set

##### X/y separation

In [5]:
from sklearn.model_selection import train_test_split

X = df.drop('y', axis=1)
y = df['y']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=42)

#### 2.4 Feature Scaling

It is always a good practice to scale the features so that all of them can be uniformly evaluated

In [6]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Artificial Neural Network : sklearn

### Part 3: Train a model

In [7]:
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)
mlp.fit(X_train, y_train)

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

### Part 4: Model Evaluation

Evaluation metrics
- confusion metrix
- accuracy
- precision, recall, f1-score

In [8]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

y_pred = mlp.predict(X_test)
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Precision: ', precision_score(y_test, y_pred))
print('Recall: ', recall_score(y_test, y_pred))
print('F1-score: ', f1_score(y_test, y_pred))

[[1478  142]
 [ 114   75]]
Accuracy:  0.8584853510226644
Precision:  0.3456221198156682
Recall:  0.3968253968253968
F1-score:  0.3694581280788177

### Part 5: Model tuning

#### Note:

After building the classifier, try answering the following questions.

1. What is the Accuracy Score?
2. If you change your preprosessing method, can you improve the model?
3. If you change your parameters setting, can you improve the model?

## Artificial Neural Network : keras
- See https://keras.io

Fitting a logistic regression model

### Part 3: Train a model

In [9]:
import keras; print(keras.__version__)

3.10.0

In [10]:
from keras import models
from keras import layers

In [11]:
X_train.shape

(2712, 48)

In [12]:
nn = models.Sequential()
nn.add(layers.Dense(48,activation = 'linear',input_shape=(None,48)))
nn.add(layers.Dense(1,activation = 'sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
nn.compile(optimizer='sgd', loss='binary_crossentropy', metrics=['accuracy'])

In [14]:
nn.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, None, 48)       │         2,352 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, None, 1)        │            49 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,401 (9.38 KB)

 Trainable params: 2,401 (9.38 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
import numpy as np
X_train_add = np.expand_dims(X_train, axis=0)
y_train_add = np.expand_dims(y_train, axis=0)

In [16]:
history = nn.fit(X_train_add,y_train_add,epochs=100)

Epoch 1/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 1s/step - accuracy: 0.5177 - loss: 0.8032
Epoch 2/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - accuracy: 0.5214 - loss: 0.7962
Epoch 3/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5225 - loss: 0.7893
Epoch 4/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5254 - loss: 0.7825
Epoch 5/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5288 - loss: 0.7758
Epoch 6/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 142ms/step - accuracy: 0.5321 - loss: 0.7693
Epoch 7/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5361 - loss: 0.7629
Epoch 8/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 179ms/step - accuracy: 0.5435 - loss: 0.7566
Epoch 9/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.5479 - loss: 0.7504
Epoch 10/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5527 - loss: 0.7443
Epoch 11/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5579 - loss: 0.7384
Epoch 12/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5623 - loss: 0.7325
Epoch 13/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5660 - loss: 0.7268
Epoch 14/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.5708 - loss: 0.7211
Epoch 15/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5756 - loss: 0.7156
Epoch 16/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5785 - loss: 0.7101
Epoch 17/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - accuracy: 0.5848 - loss: 0.7048
Epoch 18/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.5874 - loss: 0.6995
Epoch 19/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - accuracy: 0.5892 - loss: 0.6943
Epoch 20/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step - accuracy: 0.5951 - loss: 0.6893
Epoch 21/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 102ms/step - accuracy: 0.5996 - loss: 0.6843
Epoch 22/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 139ms/step - accuracy: 0.6036 - loss: 0.6793
Epoch 23/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.6088 - loss: 0.6745
Epoch 24/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - accuracy: 0.6121 - loss: 0.6697
Epoch 25/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step - accuracy: 0.6195 - loss: 0.6651
Epoch 26/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6235 - loss: 0.6605
Epoch 27/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 150ms/step - accuracy: 0.6287 - loss: 0.6559
Epoch 28/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step - accuracy: 0.6309 - loss: 0.6515
Epoch 29/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 124ms/step - accuracy: 0.6361 - loss: 0.6471
Epoch 30/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6405 - loss: 0.6428
Epoch 31/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - accuracy: 0.6445 - loss: 0.6385
Epoch 32/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.6504 - loss: 0.6344
Epoch 33/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6538 - loss: 0.6302
Epoch 34/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.6586 - loss: 0.6262
Epoch 35/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6630 - loss: 0.6222
Epoch 36/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.6689 - loss: 0.6183
Epoch 37/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6737 - loss: 0.6144
Epoch 38/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6763 - loss: 0.6106
Epoch 39/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.6833 - loss: 0.6068
Epoch 40/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.6899 - loss: 0.6031
Epoch 41/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.6951 - loss: 0.5995
Epoch 42/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6999 - loss: 0.5959
Epoch 43/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7043 - loss: 0.5923
Epoch 44/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7105 - loss: 0.5889
Epoch 45/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7139 - loss: 0.5854
Epoch 46/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7190 - loss: 0.5820
Epoch 47/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - accuracy: 0.7246 - loss: 0.5787
Epoch 48/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.7279 - loss: 0.5754
Epoch 49/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - accuracy: 0.7330 - loss: 0.5721
Epoch 50/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7378 - loss: 0.5689
Epoch 51/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7430 - loss: 0.5658
Epoch 52/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.7463 - loss: 0.5627
Epoch 53/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7485 - loss: 0.5596
Epoch 54/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7518 - loss: 0.5565
Epoch 55/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7566 - loss: 0.5536
Epoch 56/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7614 - loss: 0.5506
Epoch 57/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7662 - loss: 0.5477
Epoch 58/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7699 - loss: 0.5448
Epoch 59/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7732 - loss: 0.5420
Epoch 60/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.7769 - loss: 0.5392
Epoch 61/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7806 - loss: 0.5364
Epoch 62/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.7810 - loss: 0.5337
Epoch 63/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.7828 - loss: 0.5310
Epoch 64/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.7861 - loss: 0.5283
Epoch 65/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.7898 - loss: 0.5257
Epoch 66/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7939 - loss: 0.5231
Epoch 67/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.7968 - loss: 0.5206
Epoch 68/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.7994 - loss: 0.5180
Epoch 69/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8035 - loss: 0.5155
Epoch 70/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8079 - loss: 0.5131
Epoch 71/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8097 - loss: 0.5106
Epoch 72/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8123 - loss: 0.5082
Epoch 73/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8138 - loss: 0.5059
Epoch 74/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8142 - loss: 0.5035
Epoch 75/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8167 - loss: 0.5012
Epoch 76/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8204 - loss: 0.4989
Epoch 77/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8223 - loss: 0.4966
Epoch 78/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8245 - loss: 0.4944
Epoch 79/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8263 - loss: 0.4922
Epoch 80/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8285 - loss: 0.4900
Epoch 81/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8311 - loss: 0.4878
Epoch 82/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8326 - loss: 0.4857
Epoch 83/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8344 - loss: 0.4836
Epoch 84/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8355 - loss: 0.4815
Epoch 85/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - accuracy: 0.8370 - loss: 0.4795
Epoch 86/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - accuracy: 0.8378 - loss: 0.4774
Epoch 87/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8389 - loss: 0.4754
Epoch 88/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - accuracy: 0.8411 - loss: 0.4734
Epoch 89/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8429 - loss: 0.4714
Epoch 90/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8451 - loss: 0.4695
Epoch 91/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - accuracy: 0.8481 - loss: 0.4676
Epoch 92/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8499 - loss: 0.4657
Epoch 93/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.8499 - loss: 0.4638
Epoch 94/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8514 - loss: 0.4619
Epoch 95/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8532 - loss: 0.4601
Epoch 96/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - accuracy: 0.8540 - loss: 0.4583
Epoch 97/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - accuracy: 0.8569 - loss: 0.4565
Epoch 98/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.8573 - loss: 0.4547
Epoch 99/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.8588 - loss: 0.4529
Epoch 100/100
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.8595 - loss: 0.4512

### Part 4: Model Evaluation

In [17]:
X_test_add = np.expand_dims(X_test, axis=0)
y_test_add = np.expand_dims(y_test, axis=0)

In [18]:
test_loss, test_acc = nn.evaluate(X_test_add, y_test_add)
print('Test Loss: %s\nTest Accuracy: %s' % (test_loss,test_acc))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 214ms/step - accuracy: 0.8601 - loss: 0.4419
Test Loss: 0.4419081509113312
Test Accuracy: 0.8601437211036682

In [19]:
history.history

{'accuracy': [0.517699122428894,
  0.521386444568634,
  0.5224926471710205,
  0.5254424810409546,
  0.528761088848114,
  0.5320796370506287,
  0.5361356735229492,
  0.5435103178024292,
  0.5479351282119751,
  0.5527285933494568,
  0.5578908324241638,
  0.5623156428337097,
  0.5660029649734497,
  0.5707964897155762,
  0.5755899548530579,
  0.5785398483276367,
  0.5848082304000854,
  0.5873894095420837,
  0.5892330408096313,
  0.5951327681541443,
  0.5995575189590454,
  0.603613555431366,
  0.608775794506073,
  0.6120944023132324,
  0.6194690465927124,
  0.623525083065033,
  0.62868732213974,
  0.6308997273445129,
  0.63606196641922,
  0.6404867172241211,
  0.6445427536964417,
  0.6504424810409546,
  0.653761088848114,
  0.6585545539855957,
  0.6629793643951416,
  0.6688790321350098,
  0.6736725568771362,
  0.6762536764144897,
  0.6832596063613892,
  0.6898967623710632,
  0.6950590014457703,
  0.6998525261878967,
  0.7042772769927979,
  0.7105457186698914,
  0.7138643264770508,
  0.7190265655517578,
  0.7245575189590454,
  0.7278761267662048,
  0.7330383658409119,
  0.7378318309783936,
  0.7429941296577454,
  0.74631267786026,
  0.748525083065033,
  0.7518436312675476,
  0.7566371560096741,
  0.7614306807518005,
  0.766224205493927,
  0.769911527633667,
  0.7732300758361816,
  0.7769173979759216,
  0.7806047201156616,
  0.7809734344482422,
  0.7828171253204346,
  0.7861356735229492,
  0.7898229956626892,
  0.7938790321350098,
  0.7968289256095886,
  0.7994100451469421,
  0.8034660816192627,
  0.8078908324241638,
  0.8097345232963562,
  0.8123156428337097,
  0.8137905597686768,
  0.8141592741012573,
  0.8167403936386108,
  0.8204277157783508,
  0.8222714066505432,
  0.8244837522506714,
  0.8263274431228638,
  0.8285398483276367,
  0.8311209678649902,
  0.8325958847999573,
  0.8344395160675049,
  0.8355457186698914,
  0.8370206356048584,
  0.8377581238746643,
  0.8388643264770508,
  0.841076672077179,
  0.8429203629493713,
  0.8451327681541443,
  0.8480826020240784,
  0.849926233291626,
  0.849926233291626,
  0.851401150226593,
  0.8532448410987854,
  0.8539823293685913,
  0.8569321632385254,
  0.857300877571106,
  0.858775794506073,
  0.8595132827758789],
 'loss': [0.8032363653182983,
  0.7961889505386353,
  0.7892747521400452,
  0.782490611076355,
  0.7758331894874573,
  0.7692994475364685,
  0.7628864049911499,
  0.7565910816192627,
  0.7504104375839233,
  0.7443419098854065,
  0.7383826971054077,
  0.7325301766395569,
  0.7267816066741943,
  0.7211346626281738,
  0.7155867218971252,
  0.7101355195045471,
  0.7047787308692932,
  0.6995139122009277,
  0.6943392157554626,
  0.6892520785331726,
  0.6842508912086487,
  0.6793333292007446,
  0.6744974255561829,
  0.6697413921356201,
  0.6650632619857788,
  0.6604612469673157,
  0.6559335589408875,
  0.6514787077903748,
  0.6470947861671448,
  0.6427802443504333,
  0.6385335922241211,
  0.6343531608581543,
  0.6302375793457031,
  0.6261854767799377,
  0.6221951842308044,
  0.6182656288146973,
  0.614395260810852,
  0.6105829477310181,
  0.606827437877655,
  0.6031273603439331,
  0.5994816422462463,
  0.5958890914916992,
  0.5923486351966858,
  0.5888592004776001,
  0.5854195952415466,
  0.582028865814209,
  0.5786861181259155,
  0.5753902792930603,
  0.5721402764320374,
  0.5689354538917542,
  0.5657745599746704,
  0.5626571178436279,
  0.559581995010376,
  0.5565484762191772,
  0.5535556674003601,
  0.5506029725074768,
  0.5476893186569214,
  0.5448142886161804,
  0.5419768691062927,
  0.5391765832901001,
  0.5364127159118652,
  0.5336843729019165,
  0.5309910774230957,
  0.5283321738243103,
  0.5257070660591125,
  0.5231150388717651,
  0.5205556154251099,
  0.5180280804634094,
  0.5155320763587952,
  0.5130669474601746,
  0.5106319785118103,
  0.5082269906997681,
  0.5058512687683105,
  0.5035042762756348,
  0.5011855363845825,
  0.4988947808742523,
  0.4966312646865845,
  0.4943947196006775,
  0.4921846091747284,
  0.4900006353855133,
  0.4878421723842621,
  0.48570895195007324,
  0.4836004972457886,
  0.48151642084121704,
  0.47945636510849,
  0.47741997241973877,
  0.47540679574012756,
  0.4734165668487549,
  0.47144877910614014,
  0.4695033133029938,
  0.4675796329975128,
  0.4656774401664734,
  0.4637965261936188,
  0.46193647384643555,
  0.46009695529937744,
  0.45827773213386536,
  0.45647841691970825,
  0.4546988010406494,
  0.4529385566711426,
  0.45119738578796387]}

### Part 5: Model tuning

#### Note:

After building the classifier, try answering the following questions.

1. What is the Accuracy Score?
2. If you change your preprosessing method, can you improve the model?
3. If you change your parameters setting, can you improve the model?